CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE company (
    companyid integer GENERATED BY DEFAULT AS IDENTITY,
    companyname character varying(200),
    companyphonenumber bigint,
    CONSTRAINT "PK_company" PRIMARY KEY (companyid)
);

CREATE TABLE productcategory (
    productcategoryid integer GENERATED BY DEFAULT AS IDENTITY,
    productcategoryname character varying(100),
    CONSTRAINT "PK_productcategory" PRIMARY KEY (productcategoryid)
);

CREATE TABLE productunit (
    productunitid integer GENERATED BY DEFAULT AS IDENTITY,
    productunitname character varying(50),
    CONSTRAINT "PK_productunit" PRIMARY KEY (productunitid)
);

CREATE TABLE users (
    userid integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(120),
    useremail character varying(200),
    userpassword character varying(120),
    companyid integer,
    CONSTRAINT "PK_users" PRIMARY KEY (userid),
    CONSTRAINT "FK_users_company_companyid" FOREIGN KEY (companyid) REFERENCES company (companyid)
);

CREATE TABLE products (
    productid integer GENERATED BY DEFAULT AS IDENTITY,
    productname character varying(150),
    productcategoryid integer,
    productunitid integer,
    productprice numeric NOT NULL,
    productphotopath character varying(2000),
    dateadded timestamp with time zone,
    userid integer,
    companyid integer,
    createdat timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    addtype character varying(10) DEFAULT 'Single',
    CONSTRAINT "PK_products" PRIMARY KEY (productid),
    CONSTRAINT "FK_products_company_companyid" FOREIGN KEY (companyid) REFERENCES company (companyid),
    CONSTRAINT "FK_products_productcategory_productcategoryid" FOREIGN KEY (productcategoryid) REFERENCES productcategory (productcategoryid),
    CONSTRAINT "FK_products_productunit_productunitid" FOREIGN KEY (productunitid) REFERENCES productunit (productunitid),
    CONSTRAINT "FK_products_users_userid" FOREIGN KEY (userid) REFERENCES users (userid)
);

CREATE INDEX "IX_products_companyid" ON products (companyid);

CREATE INDEX "IX_products_productcategoryid" ON products (productcategoryid);

CREATE INDEX "IX_products_productunitid" ON products (productunitid);

CREATE INDEX "IX_products_userid" ON products (userid);

CREATE INDEX "IX_users_companyid" ON users (companyid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260716115759_InitialCreate', '10.0.10');

COMMIT;

