version: "3.9"



services:
  backend:
    build:
      context: ./ProductCatalogApi
    container_name: backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=192.168.176.1;Port=5432;Database=mydb;Username=postgres;Password=root
      MediaRoot: /app/media
    ports:
      - "5000:5000"
    volumes:
      - ./media:/app/media

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:80"
