# Generated by Django 6.0.2 on 2026-07-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('productcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('productcategoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productunit',
            fields=[
                ('productunitid', models.AutoField(primary_key=True, serialize=False)),
                ('productunitname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=150)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productphotopath', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('dateadded', models.DateField(blank=True, null=True)),
                ('productcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcategory')),
                ('productunitid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productunit')),
            ],
        ),
    ]
