# Generated by Django 6.0.2 on 2026-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=200)),
                ('companyphonenumber', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('endsuerid', models.AutoField(db_column='endsuerid', primary_key=True, serialize=False)),
                ('endusername', models.CharField(db_column='endusername', max_length=100, unique=True)),
                ('enduserpassword', models.CharField(blank=True, db_column='enduserpassword', max_length=100, null=True)),
                ('enduseremail', models.CharField(blank=True, db_column='enduseremail', max_length=100, null=True)),
                ('enduserphone', models.CharField(blank=True, db_column='enduserphone', max_length=20, null=True)),
            ],
            options={
                'db_table': 'enduser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('useremail', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('userpassword', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'managed': False},
        ),
    ]
