# Generated by Django 6.0.2 on 2026-08-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_company_enduser_users_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companycategory',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'companycategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=200)),
                ('customerphonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('customeraddress', models.CharField(blank=True, max_length=500, null=True)),
                ('customeremail', models.CharField(blank=True, max_length=200, null=True)),
                ('customercurrentbal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('customeropeningbal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('customerpincode', models.CharField(blank=True, max_length=20, null=True)),
                ('customergst', models.CharField(blank=True, max_length=50, null=True)),
                ('customerstate', models.CharField(blank=True, max_length=100, null=True)),
                ('customerpanno', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('customerbillid', models.AutoField(primary_key=True, serialize=False)),
                ('customerbillno', models.CharField(max_length=100)),
                ('customerbilldate', models.DateField()),
                ('customerbillamount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('customerbillduedate', models.DateField(blank=True, null=True)),
                ('paidamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('customerbilltype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customerbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=200)),
                ('supplierphonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('supplieraddress', models.CharField(blank=True, max_length=500, null=True)),
                ('supplieremail', models.CharField(blank=True, max_length=200, null=True)),
                ('suppliercurrentbal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('supplieropeningbal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('supplierpincode', models.CharField(blank=True, max_length=20, null=True)),
                ('suppliergst', models.CharField(blank=True, max_length=50, null=True)),
                ('isconnected', models.SmallIntegerField(db_column='isconnected', default=0)),
                ('supplierstate', models.CharField(blank=True, max_length=100, null=True)),
                ('supplierpanno', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('supplierbillid', models.AutoField(primary_key=True, serialize=False)),
                ('supplierbillno', models.CharField(max_length=100)),
                ('supplierbilldate', models.DateField()),
                ('supplierbillamount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('supplierbillduedate', models.DateField(blank=True, null=True)),
                ('paidamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('supplierbilltype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'supplierbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplieruser',
            fields=[
                ('supplieruserid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(blank=True, max_length=25, null=True)),
                ('supplierusername', models.CharField(blank=True, max_length=25, null=True)),
                ('supplieruserphone', models.CharField(blank=True, max_length=20, null=True)),
                ('supplieruseremail', models.CharField(blank=True, max_length=30, null=True)),
                ('supplierusergstnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('supplieruseraddress', models.CharField(blank=True, max_length=100, null=True)),
                ('supplieruserpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'supplieruser',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='productcategory',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productunit',
            table='productunit',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='products.company')),
                ('enduser', models.ForeignKey(db_column='endsuerid', on_delete=django.db.models.deletion.DO_NOTHING, to='products.enduser')),
            ],
            options={
                'db_table': 'conversation',
                'managed': True,
                'unique_together': {('company', 'enduser')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='products.conversation')),
            ],
            options={
                'db_table': 'chat_message',
                'managed': True,
            },
        ),
    ]
