# Generated by Django 6.0.2 on 2026-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_companycategory_customer_customerbill_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='order_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
