# Generated by Django 6.0.2 on 2026-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_chatmessage_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='waveform',
            field=models.TextField(blank=True, help_text='JSON list of waveform floats', null=True),
        ),
    ]
