# Generated by Django 6.0.2 on 2026-08-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_chatmessage_duration_chatmessage_waveform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExecutive',
            fields=[
                ('executiveid', models.AutoField(primary_key=True, serialize=False)),
                ('executive_name', models.CharField(max_length=100)),
                ('executive_username', models.CharField(max_length=100, unique=True)),
                ('executive_password', models.CharField(max_length=100)),
                ('executive_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='products.supplieruser')),
            ],
            options={
                'db_table': 'supplier_executive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='products.company')),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_taken', to='products.supplierexecutive')),
                ('supplier', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.DO_NOTHING, to='products.supplier')),
            ],
            options={
                'db_table': 'supplier_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.supplierorder')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
            ],
            options={
                'db_table': 'supplier_order_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExecutiveAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_allocations', to='products.company')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='products.supplierexecutive')),
            ],
            options={
                'db_table': 'executive_allocation',
                'managed': True,
                'unique_together': {('executive', 'company')},
            },
        ),
    ]
