# Generated by Django 6.0.2 on 2026-08-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_supplierexecutive_supplierorder_supplierorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierexecutive',
            name='supplier_user',
            field=models.ForeignKey(blank=True, db_column='supplier_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='products.supplieruser'),
        ),
        migrations.CreateModel(
            name='SupplierManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_username', models.CharField(max_length=100, unique=True)),
                ('manager_password', models.CharField(max_length=100)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_area', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_user', models.ForeignKey(db_column='supplier_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='products.supplieruser')),
            ],
            options={
                'db_table': 'supplier_manager',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='supplierexecutive',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='products.suppliermanager'),
        ),
    ]
