# Generated by Django 6.0.2 on 2026-08-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_supplierexecutive_supplier_user_suppliermanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, help_text='Specific price offered by this supplier', max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, to='products.company')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('supplier', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
            options={
                'db_table': 'supplier_product',
                'managed': True,
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
