# Generated by Django 6.0.6 on 2026-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_supplierproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('commitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(db_index=True, max_length=100)),
                ('bill_id', models.IntegerField(blank=True, db_column='supplierbillid', null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('previous_due_date', models.CharField(blank=True, default='', max_length=50)),
                ('new_due_date', models.CharField(blank=True, default='', max_length=50)),
                ('bill_due_date', models.DateField(blank=True, null=True)),
                ('extension_days', models.IntegerField(default=0)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commitment',
                'managed': True,
            },
        ),
    ]
