# Generated by Django 6.0.6 on 2026-09-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderitem',
            name='supplier_product',
            field=models.ForeignKey(blank=True, db_column='supplierproductid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplierproduct'),
        ),
    ]
