# Generated by Django 6.0.6 on 2026-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_supplierorderitem_supplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFCMToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=50)),
                ('fcm_token', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_fcm_token',
                'managed': True,
                'unique_together': {('user_id', 'user_type')},
            },
        ),
    ]
